plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\Downloads\\Installers\\Open Code\\ALL Project inside\\Project 1\\age_calculator"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]